Change exit code to 1 and add failure handling step

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -28,4 +28,7 @@ jobs:
           DB_PASS: ${{secrets.DB_PASSWORD}}
         run: echo "DB Password is set"
       - name: Failing on purpose
-        run: exit 0
+        run: exit 1
+      - name: If failed
+        if: failure()
+        run: echo "Can this really work out at the end ?"
